defaultBaseImage: registry.access.redhat.com/ubi9/ubi-minimal

baseImageOverrides:
  github.com/shipwright-io/build/cmd/bundle: ghcr.io/shipwright-io/base-base:ubi9-latest
  github.com/shipwright-io/build/cmd/git: ghcr.io/shipwright-io/base-git:ubi9-latest
  github.com/shipwright-io/build/cmd/image-processing: ghcr.io/shipwright-io/base-image-processing:ubi9-latest
  github.com/shipwright-io/build/cmd/waiter: ghcr.io/shipwright-io/base-waiter:ubi9-latest
