defaultBaseImage: registry.access.redhat.com/ubi10:10.0-1747220028

baseImageOverrides:
  github.com/shipwright-io/build/cmd/bundle: ghcr.io/shipwright-io/base-base:ubi10-latest
  github.com/shipwright-io/build/cmd/git: ghcr.io/shipwright-io/base-git:ubi10-latest
  github.com/shipwright-io/build/cmd/image-processing: ghcr.io/shipwright-io/base-image-processing:ubi10-latest
  github.com/shipwright-io/build/cmd/waiter: ghcr.io/shipwright-io/base-waiter:ubi10-latest
