name: Base images build

on:
  schedule:
  - cron: '0 3 * * *' # 3 AM UTC = before the nightly build
  workflow_dispatch:  # Manual trigger
  push:
    branches: [test]

jobs:
  base-image-build:
    if: ${{ github.ref == 'refs/heads/test' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - base
          - git
          - image-processing
          - waiter
        tags: [latest, ubi10] 
        include:
          - image: git
            tags: latest
            dockerfile: Dockerfile.ubi9
          - image: git
            tags: ubi10
            dockerfile: Dockerfile
      max-parallel: 1

    steps:
      - uses: actions/checkout@v4

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        run: echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USERNAME }} --password-stdin quay.io

      - name: Build Image
        working-directory: images/${{ matrix.image }}
        run: |
          if [[ "${{ matrix.tags }}" == "ubi10" ]]; then
          BUILD_IMAGE="registry.access.redhat.com/ubi10:10.0-1747220028"
          else
          BUILD_IMAGE="registry.access.redhat.com/ubi9:9.6-1749542372"
          fi
          NAMESPACE="shipwright-io" \
          IMAGE=quay.io/r3hankhan/${NAMESPACE}/base-${{ matrix.image }}  \
          TAG=${{matrix.tags}} BUILD_IMAGE=$BUILD_IMAGE DOCKERFILE=${{matrix.dockerfile || 'Dockerfile' }} docker buildx bake --push -f ../docker-bake.hcl
