name: Base images build

on:
  schedule:
  - cron: '0 3 * * *' # 3 AM UTC = before the nightly build
  workflow_dispatch:  # Manual trigger
  push:
    branches: [test]

jobs:
  base-image-build:
    if: ${{ github.ref == 'refs/heads/test' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - base
          - git
          - image-processing
          - waiter
      max-parallel: 1

    steps:
      - uses: actions/checkout@v4

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        run: echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USERNAME }} --password-stdin quay.io

      - name: Build Image
        working-directory: images/${{ matrix.image }}
        run: |
          NAMESPACE="shipwright-io" \
          TAG=latest \
          IMAGE=quay.io/r3hankhan/${NAMESPACE}/base-${{ matrix.image }} NAMESPACE="${NAMESPACE}" TAG="${TAG}" docker buildx bake --push -f ../docker-bake.hcl

      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: release-v0.16

      - name: Build and push the image with the release tag
        working-directory: images/${{ matrix.image }}
        run: |
          # Define the base image repository name
          IMAGE_REPO_NAME="quay.io/r3hankhan/shipwright-io/base-${{ matrix.image }}"
          # Define the desired tag
          RELEASE_TAG="v0.16"

          # Use docker buildx bake and pass the variables correctly
          # The values set here will correspond to the variable "IMAGE" and "TAG" in your bake file
          docker buildx bake --push \
            -f ../docker-bake.hcl \
            --set all.IMAGE=${IMAGE_REPO_NAME} \ # Pass the full repository name to bake file's IMAGE variable
            --set all.TAG=${RELEASE_TAG}        # Pass the desired tag to bake file's TAG variable
